trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SomeTask
  - task: QodanaScan@2025
    inputs:
      args: -l,jetbrains/qodana-<linter>:2025.3
      # In 'prMode: true' Qodana checks only changed files
      prMode: false,
      postPrComment: true
      # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
      uploadResult: false
      # quick-fixes available in Ultimate and Ultimate Plus plans
      pushFixes: 'none'
    env:
      QODANA_TOKEN: $(QODANA_TOKEN)