trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: SomeTask
  - task: QodanaScan@VERSION_PLACEHOLDER
    inputs:
      args: -l,jetbrains/qodana-<linter>:LINTER_PLACEHOLDER
      # When prMode is set to true, Qodana analyzes only the files that have been changed
      prMode: false,
      postPrComment: true
      # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
      uploadResult: false
      # quick-fixes available in Ultimate and Ultimate Plus plans
      pushFixes: 'none'
    env:
      QODANA_TOKEN: $(QODANA_TOKEN)