# some unrelated component
include:
  - component: $CI_SERVER_FQDN/your-group/gradle-build-publish/gradle-build-publish@1.0

qodana:
  image:
    name: jetbrains/qodana-<linter>
    entrypoint: [""]
  cache:
    - key: qodana-2023.2-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2023.2-$CI_DEFAULT_BRANCH-
        - qodana-2023.2-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: $qodana_token