#-------------------------------------------------------------------------------#
#        Discover additional configuration options in our documentation         #
#       https://www.jetbrains.com/help/qodana/qodana-azure-pipelines.html       #
#-------------------------------------------------------------------------------#

trigger:
  - main

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    fetchDepth: 0
  - task: Cache@2  # Not required, but Qodana will open projects with cache faster.
    inputs:
      key: '"$(Build.Repository.Name)" | "$(Build.SourceBranchName)" | "$(Build.SourceVersion)"'
      path: '$(Agent.TempDirectory)/qodana/cache'
      restoreKeys: |
        "$(Build.Repository.Name)" | "$(Build.SourceBranchName)"
        "$(Build.Repository.Name)"
  - task: QodanaScan@VERSION_PLACEHOLDER
    inputs:
      args: --baseline,qodana.sarif.json,-l,jetbrains/qodana-<linter>:LINTER_PLACEHOLDER
      # When prMode is set to true, Qodana analyzes only the files that have been changed
      prMode: false,
      postPrComment: true
      # Upload Qodana results (SARIF, other artifacts, logs) as an artifact to the job
      uploadResult: false
      # quick-fixes available in Ultimate and Ultimate Plus plans
      pushFixes: 'none'
    env:
      QODANA_TOKEN: $(QODANA_TOKEN)